// Code generated by hero.
// source: C:\Go\dev\src\fasthttp\template\errors\404.html
// DO NOT EDIT!
package template

import "bytes"

func Error(buffer *bytes.Buffer) {
	buffer.WriteString(`
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
  <style type="text/css">
    html, body {
      height: 100%;
    }

    body {
      margin: 0;
      padding: 0;
      width: 100%;
      color: #3B3B3B;
      display: table;
      font-weight: 700;
      font-family: 'Lato', sans-serif;
    }

    .container {
      text-align: center;
      display: table-cell;
      vertical-align: middle;
    }

    .content {
      text-align: center;
      padding: 10px 50px;
      display: inline-block;
    }

    .title {
      font-size: 2.8em;
      margin-bottom: 40px;
    }
    
    .logo {
      max-width: 300px;
      margin: 0 auto;
    }
    
    .logo img {
      width: 100%;
      height: 100%;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="content">
      <div class="title">Not Found</div>
    </div>
  </div>
</body>
</html>

`)

}
