runtime: go                     # see https://cloud.google.com/appengine/docs/go/
api_version: go1.8                # used when appengine supports different go versions
manual_scaling:
  instances: 1

handlers:
- url: /(.*\.(js))$
  static_files: dist/\1
  upload: dist/.*\.(js)$

- url: /(.*\.(css))$
  static_files: dist/\1
  upload: dist/.*\.(css)$

- url: /(.*\.(woff|svg|ttf))$
  static_files: dist/\1
  upload: dist/.*\.(woff|svg|ttf)$

- url: /(.*\.(png|jpeg|jpg|gif))$
  static_files: dist/\1
  upload: dist/.*\.(png|jpeg|jpg|gif)$

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    X-Frame-Options: ALLOWALL
  
skip_files:
- node_modules/
- src/
- .vscode/
- tools/